# Generated by Django 3.1.7 on 2021-03-06 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatekeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=194, verbose_name='nome completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('phone', models.CharField(max_length=11, verbose_name='telefone')),
                ('birth_date', models.DateField(verbose_name='data de nascimento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Porteiro',
                'verbose_name_plural': 'Porteiros',
            },
        ),
    ]
