# Generated by Django 3.1.7 on 2021-03-06 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatekeepers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=194, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('number_home', models.PositiveSmallIntegerField(verbose_name='Número da casa a ser visitada')),
                ('vehicle_plate', models.CharField(blank=True, max_length=7, null=True, verbose_name='Placa do veículo')),
                ('arrival_time', models.DateTimeField(auto_now_add=True, verbose_name='Horário de chegada na portaria')),
                ('departure_time', models.DateTimeField(blank=True, null=True, verbose_name='Horário de saida do condominio')),
                ('authorization_time', models.DateTimeField(blank=True, null=True, verbose_name='Horário de autorização de entrada')),
                ('responsible_resident', models.CharField(blank=True, max_length=194, null=True, verbose_name='Nome do morador responsável por autorizar a entrada do visitante')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gatekeepers.gatekeeper', verbose_name='Porteiro responsável pelo registro')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
            },
        ),
    ]
